{% set version = "1.0-23" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mpm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mpm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mpm/mpm_{{ version }}.tar.gz
  sha256: d2abda28246842b187b796a730c6e0590182960fda3bbf16ce4a1d5e5b13fbca

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-kernsmooth
    - r-mass
  run:
    - r-base
    - r-kernsmooth
    - r-mass

test:
  commands:
    - $R -e "library('mpm')"           # [not win]
    - "\"%R%\" -e \"library('mpm')\""  # [win]

about:
  home: http://mpm.r-forge.r-project.org
  license: GPL-2.0-or-later
  summary: 'Exploratory graphical analysis of multivariate data, specifically gene expression data with different projection methods: principal component analysis, correspondence analysis, spectral map analysis.'
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - ArneKr
    - FrodePedersen
    - MathiasHaudgaard

# Package: mpm
# Version: 1.0-22
# Date: 2011-11-23
# Title: Multivariate Projection Methods
# Author: Luc Wouters <wouters_luc@telenet.be>
# Maintainer: Tobias Verbeke <tobias.verbeke@openanalytics.eu>
# Depends: R (>= 2.10), MASS, KernSmooth
# Description: Exploratory graphical analysis of multivariate data, specifically gene expression data with different projection methods: principal component analysis, correspondence analysis, spectral map analysis.
# License: GPL (>= 2)
# URL: http://mpm.r-forge.r-project.org
# Collate: 'export.summary.mpm.R' 'Famin81A.R' 'Golub.R' 'mpm.R' 'plot.mpm.R' 'print.mpm.R' 'print.summary.mpm.R' 'summary.mpm.R' 'zzz.R'
# Packaged: 2011-11-25 13:12:59 UTC; tobias
# Repository: CRAN
# Date/Publication: 2011-11-25 15:55:57
