travis:
  secure:
    BINSTAR_TOKEN: zDZpwM2cefMLszBWcAxZJgfw5w6TYFrMkbzr1FVUbbA6wLxlQ6fzUAnbiIbz8Np45LhfPlrGNTsvb3+tbjD3hRbRaFIL+03e53zsjzs0HuNQkhbf3Mfh+PqdgnPzcsGl1zsUs40+ULXhtFI9hjw4Ughw5GNQFxlZkk++0bpL8U8zAiVVsQCFG54GSLoU0/wtr3JH+c9hyYSjZdUpePT8bhltzthR5eVZH1tCJVNzf5C9Tj0BHdzBzk2jKgaNyx/r0B6XKXtqudf1hPP8dJNZZ67S3LhKiYoxgle0QL7mKTx7kqXW+emwfOp8AiFA9ss4NaUSv7ed5hRNvh9/qxcUa/bpP94YRKZuoXd5/tJL38AKQ4ZP1YDHlRnNjgNLKv7OrV4cu+A6FkIEppBTg49fC7gEtd5ZmWFUtS0zbOd5bFp8nXa3A/xb2KQw7Ju45eUCHGHDgOh8YLRRPq4hmQHhjgfe1yc/rzA3W+WDsd755k7IpN0CevsgSG28TYJDcRgwDd1bsHmJFTGGh7s4exhakNG/zLG3ABBUQiaYSKh2mzNyb6Kiv5Ju5mykiV9G/3T7Lgq4YfuBNeLPsBRXa84FUJxzTtVf5h8l6K9649t7a8tpWkS0BMK6eZwtQdzWlAvM+DvTtm+R31cxTD5j6g1letl36fcvvOkHH0TGlGIau1k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
