travis:
  secure:
    BINSTAR_TOKEN: mVORNh3VUIvQVKHpQL5cj3t+B04dbiJOeS5DrFH2h55//2y/LP7jPAYczKwfsl60sUlH0/avax0oLgE5LbzT6lK5Vn43LkKawOvj1KEc7IQThEhzkqjqgjMhGOC2562vsz8zwOwUH5hKlnrdOsteQf56NtmSBm+oa5VxGlvAccRHt9YGuxvnKAUXviw7fSxhi8Bh0X4rcurjni4JTiMAT6/eKmusEaZ6sXh8p42tzbo4mKve0AoA4NOdrjVFwEwqgndwoO2auYg9A40MbJjb13zyl/bsSZjOnquEckt7NurVccIN0HwS2XH2eD7Qhx0L+s5ai9tCi//xcq2mkZmsngHtUXc5TL1wijxAp6qR62NKD6AhQLC4ms4st1AXthSzW0yHXZln5FOkFe4pPTyjbW5xNargsKBbv6TQ7gC1sA6unHYDhbQzz0h5tmzU4DDnuquEf1qPUifyMXOXX/t18BX+vrL5x7IISEmUUinMmx4Gqn0/vSlezIe9nHUtLqx2FfOLqU7NDl/L9g/W9n2W9rGeMQ2G87020Hkwfa2JGnHvKqjQ+exj9b8n7txBvqQds1uIKJJCvN3lPWOtgLQyobCnQ9iPISi/MbwzoEH1nViRow7sHM/RZbFw/nhoMJH3Ok7yh5caOnKWXUmv5XlZaUFluqbFlTjEHZsLXZHwe+o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
